export enum ErrorCode {
    DB_ERROR = 1,
    SERVER_ERROR,
    TOKEN_NOT_FOUND,
    NO_STRATEGIES,
    NO_OFFERS,
    STRATEGIY_NOT_FOUND,
    HOLDINGS_NOT_FOUND,
    OFFER_NOT_FOUND,
    OFFER_WRONG_TYPE,
    NOT_FOUND,
    ORDER_ALREADY_EXISTS
}
